apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mynode
  name: mynode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynode
  template:
    metadata:
      labels:
        app: mynode
    spec:
      containers:
      - name: mynode
        image: gcr.io/radiant-galaxy-247914/mynode:v1         
        ports:
          - containerPort: 8000

